#!/bin/bash -e
PATH=$PATH:/usr/local/bin

die () {
	echo "Usage: $0 [/path/to/databrary-VER.tgz|[databrary-]VER] MODE ..."
	exit 2
}

if [[ $1 = */databrary-*.zip && -r $1 ]] ; then
	src=$1
	base=${src%.zip}
	ver=${base##*/databrary-}
	unzip $src
	shift
elif [[ $1 = */databrary-*.tgz && -r $1 ]] ; then
	src=$1
	base=${src%.tgz}
	ver=${base##*/databrary-}
	tar xf $src
	shift
elif [[ -n $1 && -d databrary-$1 ]] ; then
	ver=$1
	shift
elif [[ $1 = databrary-* && -d $1 ]] ; then
	ver=${1#databrary-}
	shift
fi

if [[ -n $ver ]] ; then
	ln -sfT databrary-$ver databrary
fi

mode=prod
if [[ $1 = prod || -f ${1}.conf ]] ; then
	mode=$1
	shift
fi

if [[ ! -r ${mode}.conf ]] ; then
	echo "${mode}.conf does not exist."
	if [[ ! -f ${mode}.conf.example ]] ; then
		umask 077
		cat <<EOF >>${mode}.conf.example
include "/application.conf"
application.secret="`openssl rand -base64 48`"
db.default.user=$USER
db.default.password="database password"
store.master="./store"
store.cache="./cache"
http.port=8000
EOF
		echo "An example has been put in ${mode}.conf.example."
	fi
	exit 1
fi

if [[ ! -d databrary ]] ; then
	echo "No databrary found."
	die
fi

declare -a args
addargs() {
	args=("${args[@]}" "$@")
}
if [[ $USER = databrary && $mode = prod ]] ; then
	addargs -mem 2048
fi
addargs "-Dapplication.mode=$mode" "-Dconfig.file=${mode}.conf" "-Dpidfile.path=$HOME/${mode}.pid" "-Dplay.http.sslengineprovider=site.PoodleSSLEngineProvider"
while read l ; do
	if [[ $l = http*=* || $l = java.*=* ]] ; then
		addargs "-D$l"
	fi
done < ${mode}.conf
if [[ -f ${mode}-logger.xml ]] ; then
	addargs "-Dlogger.file=${mode}-logger.xml"
fi

exec databrary/bin/databrary "${args[@]}" "$@"
