#!/bin/sh -ex
ghc -Wall -fwarn-tabs --make Setup.hs
[[ -f dist/setup-config ]] || ./Setup configure --user -f devel
./Setup build
databrary_datadir=. databrary_sysconfdir=. dist/build/databrary/databrary "$@"
