#!/bin/bash -e
set -o pipefail

top=`git rev-parse --show-cdup`
conf=${top}conf
db=default
evolutions=$conf/evolutions/$db

getconfig () {
	# This isn't perfect but hopefully good enough
	sed -n '/^'"$1"'=\("\([^"]*\)"\|\([^# ]*\)\).*$/{s//\2\3/;p;q}' ${top}local.conf $conf/application.conf
}

getdbconfig () {
	getconfig "db\.$db\.$1"
}

getdb () {
	sed -n '/^jdbc:postgresql:\(\/\/\([^\/:]\+\)\(:\([0-9]\+\)\)\?\/\)\?\([^?]*\).*$/{s//host="\2";port="\4";database="\5"/;p}'
}

eval $(getdbconfig url | getdb)
user=`getdbconfig user`
password=`getdbconfig password`
secret=`getconfig 'application\.secret'`
: ${host:=localhost} ${port:=5432} ${database:=$user}

if [[ $secret != databrary ]] ; then
	echo -n "This looks like a production environment. Continue? "
	read y
	[[ $y = y* ]] || exit 8
fi

if [[ ! -f ~/.pgpass ]] ; then
	um=`umask -p`
	umask 077
	echo "$host:$port:$database:$user:$password" >> ~/.pgpass
	$um
fi

args=(-h $host -p $port -U $user $database)
while [[ $1 = -?* ]] ; do
	args=("${args[@]}" $1)
	shift
done

runsql () {
	psql -q "${args[@]}" -vON_ERROR_STOP=on -f "${@:--}"
}

dbreset () {
	if [[ -z $1 ]] ; then
		pg_dump -Fc -f unreset.dump "${args[@]}"
	fi
	runsql - -a <<EOF
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
EOF
}

declare -A evoexpr=([up]='0,/^# --- !Ups$/d;/^# --- !Downs$/,$d' [down]='1,/^# --- !Downs$/d')
evolve () {
	local evo=$evolutions/$2.sql
	sed -n "${evoexpr[$1]}"';/^#/d;s/;;/;/g;p' $evo | runsql
}

evolve_all () {
	n=1
	while [[ -f $evolutions/$n.sql ]] ; do
		evolve up $n
		: $[n++]
	done
}

if [[ $# -eq 0 ]] ; then
	echo "Use '$0 help' for help"
	exec psql "${args[@]}"
elif [[ $# -eq 1 && ( $1 = - || -f $1 ) ]] ; then
	runsql "$1"
elif [[ $# -eq 1 && $1 = reset ]] ; then
	dbreset
elif [[ $# -eq 1 && $1 = schema ]] ; then
	dbreset
	runsql $conf/schema.sql
elif [[ $# -eq 1 && $1 = up ]] ; then
	dbreset
	evolve_all
elif [[ $# -eq 2 && ( $1 = up || $1 = down ) ]] ; then
	evolve "$@"
elif [[ $1 = check ]] ; then
	dbreset
	runsql $conf/schema.sql
	pg_dump -O -f $conf/check-schema.sql "${args[@]}"
	dbreset 1
	evolve_all
	pg_dump -O -f $conf/check-evolve.sql "${args[@]}"
	diff -F'^[A-Z]' -u0 $conf/check-evolve.sql $conf/check-schema.sql
	echo "OK!"
	rm -f $conf/check-evolve.sql $conf/check-schema.sql
elif [[ $1 = dump ]] ; then
	shift
	exec pg_dump "${args[@]}" "$@"
else
	cat <<EOF
Usage:
  runsql  		run psql interactively
  runsql -|<file>	execute contents of file
  runsql reset		reset the database (clear public schema)
  runsql schema		apply master schema
  runsql up|down NUM	run evolution NUM (no play_evolutions)
  runsql check		apply and compare master schema and evolutions
  runsql dump ARGS...	run pg_dump
Any non-argument options are passed to the run command.
EOF
fi
