#!/bin/sh

#PBS -j oe
#PBS -o log/${PBS_JOBNAME}_${PBS_JOBID}.log
#PBS -q ser2
#PBS -l nodes=1:ppn=1,mem=1024mb

file=$FILE
dir=`dirname $file`
tdir=$dir/transcoded
base=`basename $file`
base=${base%.*}
out=$tdir/$base-01.mp4
trap 'rm -f $tdir/.$base.lock' EXIT
echo "Transcoding $file"
ls -l $file
time ffmpeg -loglevel warning -threads 1 -i "$file" -threads 1 -c:v libx264 -c:a libfdk_aac -y "$out"
