#!/bin/bash
set -o pipefail

if [[ $# -eq 1 ]] ; then
	f=`basename "$1"`
	f="transcoded/`dirname "$1"`/${f%.*}-01.mp4"
	[[ -f $f ]] && set -- "$1" "$f"
fi
if [[ $# -ne 2 ]] ; then
	echo "Usage: $0 FILE1 FILE2" >&2
	exit 1
fi

probe () {
	declare -gA "$1"
	while IFS== read k v ; do
		eval "$1[$k]=$v"
	done < <( ffprobe -loglevel warning -show_format -show_streams -of flat -i "$2" ; echo "status=$?" )
	eval "[[ $1[status] -eq 0 ]]" || exit 1
}

get () {
	eval "$1=\${$2[\$3]}"
}

set () {
	eval "$1[\$2]=\$3"
}

count_streams () {
	local i n f
	get n $1 format.nb_streams
	for (( i=0 ; i<n ; i++ )) ; do
		get f $1 streams.stream.$i.codec_type
		eval "(( c=$1[format.nb_streams.$f]++ ))"
		set $1 format.streams.$f.$c $i
	done
}

get_both () {
	get "a$1" a "$2"
	get "b$1" b "$2"
}

bad () {
	echo "$@"
	exit 1
}

probe a "$1"
probe b "$2"
count_streams a
count_streams b

for t in video audio ; do
	get_both n format.nb_streams.$t
	if [[ $an -ne $bn ]] ; then
		bad "Number of $t streams differ: $an $bn"
	fi
done

if [[ ${a[format.nb_streams.video]} -eq 0 ]] ; then
	bad "No video streams."
fi

for (( i=0 ; i<a[format.nb_streams.video] ; i++ )) ; do
	get_both v format.streams.video.$i
	get aa a streams.stream.$av.avg_frame_rate
	get ba b streams.stream.$bv.avg_frame_rate
	da=`bc <<< "scale=2;da=$aa-$ba;da<-0.1||da>0.01"` # not a typo: assymetric comparison
	if [[ -z $da || $da -ne 0 ]] ; then
		bad "Mismatching avg frame rates on video stream $i: $aa $ba"
	fi
	get ar a streams.stream.$av.r_frame_rate
	get br b streams.stream.$bv.r_frame_rate
	if [[ $ar != $br ]] ; then
		bad "Mismatching base frame rates on video stream $i: $ar $br"
	fi
done

get_both s format.start_time
get_both d format.duration
dt=`bc <<< "dt=$ad-$bd;dt<-0.5||dt>0.05"`
if [[ -z $dt || $dt -ne 0 ]] ; then
	bad "Lengths differ: $as-$ad $bs-$bd"
fi

if [[ $ad = 0* ]] ; then
	bad "Too short: $ad"
fi
