#!/bin/bash
# Transcode job management.
# This is run on transcode.host, called from conf/transctl.sh

base=$(realpath `dirname $0`)

while getopts 'a:d:hk:r:' opt ; do case "$opt" in
	a) aid=$OPTARG ;;
	d) cd $OPTARG ;;
	h) hpc=1 ;;
	k) kill=$OPTARG ;;
	r) url=$OPTARG ;;
esac ; done

if [[ $# -ge $OPTIND || -z $aid || -z $kill && -z $url ]] ; then
	echo "$0: usage error: $*"
	exit 1
fi

IN=$aid
OUT=${aid}.mp4

if [[ -n $kill ]] ; then
	if [[ -n $hpc ]] ; then
		qdel $kill
	else
		kill $kill
	fi
	rm "$IN" "$OUT"
	exit 0
fi

if [[ ! -f $IN ]] ; then
	echo "$IN: file not found"
	exit 1
fi

if [[ -n $hpc ]] ; then
	rate=50000
	sec=$[60+`stat -c %s "$IN"`/$rate]
	exec qsub -d "$PWD" -q ser2 -N "$aid" -v "aid=$aid,url=$url" -l walltime=$sec "$base/transcode.pbs"
fi

sleep 5 # hope server knows job has started by now
time ffmpeg -loglevel warning -threads 1 -i "$IN" -vf pad='iw+mod(iw\,2):ih+mod(ih\,2)' -threads 1 -c:v libx264 -c:a libfdk_aac -y "$OUT"
r=$?
if [[ $r -ne 0 ]] ; then
	rm "$OUT"
fi
curl -k -d "r=$r" "$url"
