#!/bin/bash -e

while getopts 'a:f:h:' opt ; do case "$opt" in
	a) aid=$OPTARG ;;
	f) src=$OPTARG ;;
	h) host=$OPTARG ;;
esac ; done
shift $[OPTIND-1]

if [[ $# -ne $OPTIND || -z $aid || -z $src ]] ; then
	echo "$0: usage error: $*"
	exit 1
fi

if [[ -n $host ]] ; then
	rsync $src $host:databrary/$aid
	exec ssh $host dbtranscode $aid
fi


